#!/bin/sh

# wget parameter http://stackoverflow.com/questions/3742983/how-to-get-the-contents-of-a-webpage-in-a-shell-variable

# oneliner solution
#wget http://www.meteochile.gob.cl/js/condicionactualmetar.js -q -O - | grep 'SCQN' | awk -F'|' '{print $7}'

# long solution

URL='http://www.meteochile.gob.cl/js/condicionactualmetar.js'
SANTIAGO_CODE='SCQN'

INFO=$(wget $URL -q -O - | grep $SANTIAGO_CODE)
TEMPERATURE=$(echo $INFO | awk -F'|' '{print $7}')

#CONDITION=$(echo $INFO | awk -F'|' '{print $11}')
#echo $INFO
SYMBOL='☀' # Todo: Add Condition for the symbols☂ ☀ ☁ ☃

echo "$SYMBOL $TEMPERATURE"
