config:
  fallback-icon: "?" # icon to use if no definition is found
  multi-pane-icon: "" # icon to use for window with multiple panes, if not specified, only active pane's icon will used as the default.
  show-name: false # show the window name with the icon

